name: dart_server
description: An basic webserver in dart.
#version 1.0.0
#homepage: https://www.example.com
#author: NorthernL1ghts <www.github.com/NorthernL1ghts>

enviroment:
sdk: '>=2.0.0-dev.60.0 <2.0.0'

dependencies:
  http_server: any
  
 dev_dependencies:
  build_web_compilers: ^0.4.0
